# Generated by Django 4.2.2 on 2023-06-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=100)),
                ('pid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pname', models.CharField(max_length=100)),
                ('prise', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_catagory')),
            ],
        ),
    ]
